version: '3'

services:
  registry:
    image: registry:2.8.3
    restart: always
    container_name: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry_cert_ca_root.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/registry_private.key
      #REGISTRY_HTTP_SECRET: 123
    volumes:
      - ./data:/data
      - ./auth:/auth
      - ./certs:/certs
      #- ./config.yml:/etc/docker/registry/config.yml
