apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-conf-configmap
  namespace: haproxy
data:
  haproxy.cfg: |
    global
      log 127.0.0.1   local0
      log 127.0.0.1   local1 notice
      maxconn 4096
      #chroot /var/lib/haproxy
      user haproxy
      group haproxy
      daemon
      #debug
      #quiet
    
    defaults
      log     global
      mode    http
      option  httplog
      option  dontlognull
      option redispatch
      retries 3
      maxconn 2000
      #contimeout      5000
      #clitimeout      50000
      #srvtimeout      50000
    
    listen stats
      mode  http
      bind  *:443
      stats enable
      stats hide-version
      stats uri /stats
      stats refresh 5s
