apiVersion: v1
kind: Service
metadata:
  name: service-haproxy
  namespace: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - name: nodeport
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
#  type: LoadBalancer
