version: '3.9'

services: 
  haproxy:
#    image: haproxy:1.8.27
    image: haproxy:2.4.4
    container_name: haproxy
    ports:
      - "8080:8080"
      - "443:443"
    #volumes: 
      #- ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      #- ./key.pem:/etc/haproxy/cert/key.pem
