version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/Script.py --master -H http://master:8089 #--web-host=0.0.0.0
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/Script.py --worker --master-host master --loglevel DEBUG --csv=full-history
