version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "4001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "4002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "4003:3000"

  nginx:
    container_name: nginx
    image: nginx:1.27.2-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs/nginx-selfsigned.crt:/opt/apps/certs/nginx-selfsigned.crt:ro
      - ./nginx-certs/nginx-selfsigned.key:/opt/apps/certs/nginx-selfsigned.key:ro
