name: Docker Compose Workflow

on:
  push:
    paths:
      - 'docker-compose/**'

jobs:
#  test-docker-compose:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Run Docker Compose example
#        run: docker-compose -f docker-compose/nginx/docker-compose.yml up --build -d

  test-docker-compose:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build
      - name: Run Docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml ps
          sleep 30
